apiVersion: v1
kind: Pod
metadata:
  name: client1
  labels:
    app: client1
spec:
  containers:
    - name: nodeapp1
      image: elbarnaki/nodeapp:tagVersion
      ressources:
        requests:
           memory: "64Mi"
           cpu: "250m"
        limits:
           memory: "128Mi"
           cpu: "500m"
      ports:
        - containerPort: 8000
