apiVersion: apps/v1
kind: deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: elbarnaki/nodeapp:tagVersion
      ports:
        - containerPort: 8000